version: "3"
services:
  phoenix:
    container_name: phoenix-server
    build: .
    expose: 
      - 8080 
    ports:
      - "8080:8080"
    restart: on-failure 
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    container_name: phoenix-db
    image: "postgres:11.2-alpine"
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - .env
